### ISSUE TITLE
Export Mapzen&Vallhalla API Key to Gui

### ISSUE THREAD

**Issue by jaykijay** [rinigus/poor-maps#42]
Hi,
thanks for this nice App :)
As you mentioned, Mapzen has a limited free Access to their API and will block after this.
Maybe it could be possible to make the API Keys not fixed in the .py script but instead put it to a variable which can be exported and changed in the Gui. Something like a special Dev Mode fpr Poo Maps which allows anyone with enough skill to use their own Api Keys instead of yours.
I don't know if this is allowed in License Terms, i don't think so, but if it is, it would be a very nice backdoor to use it after we hit the Limit for free Access.
Thanks for all your work :)

**Comment by rinigus** [comment]
Hi,

thank you for suggestion - I am quite sure its against their policy, or at least idea behind it. They do provide service and if we use it in larger amounts we should probably pay as well :). According to @otsaloma's stats, we are not close to 50K map tile downloads, no idea regarding other calls. Right now, we are at the rate of ~650 tiles per day, so we are quite safe now. 

I am working on tuning offline map import and styles. There is a lot of work needed still, but good quality offline maps should help to reduce online use. When we start hitting the limits, we would probably have to evaluate on whether pay for service, setup our own servers, or combination of the above. @otsaloma already setup a server for providing tiles to reduce this issue.

I wouldn't implement such GUI as a part of GL branch. Its a decision that will ultimately will be done by @otsaloma as a part of Poor Maps successor development. We just have to be ready to provide our support when needed. 

I am going to close it as an issue. We could discuss it on TMO or later as a part of Poor Maps upstream issues. Thank you again for suggestion!
